platform :ios, '12.0'

target 'HCKalmanFilter Sample' do    
	use_frameworks!
	inhibit_all_warnings!

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    
    pod 'ActionSheetPicker-3.0', '~> 2.5.0'

    pod 'Surge', '~> 2.3'    
end

